---
version: '3'
services:
  girder:
    volumes:
      # For local development, uncomment the set of mounts associated with the
      # local source files.  Adding the editable egg directories first allows
      # allow mounting source files from the host without breaking the internal
      # data.
      #- /home/dagutman/devel/dsa-wsi-deid:/opt/dsa-wsi-deid
      #- /home/dagutman/devel/nci-dsa-deid:/opt/nci-dsa-deid
      - ./wsi_deid_provision.py:/opt/digital_slide_archive/devops/dsa/wsi_deid_provision.py
      - ./provision.py:/opt/digital_slide_archive/devops/dsa/provision.py
      - ./importManifestSchema.json:/opt/digital_slide_archive/devops/dsa/importManifestSchema.json
      - ./provision.yaml:/opt/digital_slide_archive/devops/dsa/provision.yaml
      - /home/dagutman/Insync/DGUTMAN@emory.edu/OneDrive Biz - Shared:/dermImages
      - ./homepage.md:/opt/digital_slide_archive/devops/dsa/homepage.md
      - /home/dagutman/data/import:/import
      - /home/dagutman/data/export:/export
      - /home/dagutman/devel/nci-dsa-deid:/opt/nci-dsa-deid
    #    command: bash -c 'PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH" pip install /opt/nci-dsa-deid && PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH" python /opt/digital_slide_archive/devops/dsa/wsi_deid_provision.py && /opt/digital_slide_archive/devops/dsa/start_girder.sh '
    command: bash -c 'PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH" pip install -e /opt/nci-dsa-deid && PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH"  /opt/digital_slide_archive/devops/dsa/start_girder.sh ' # system.  Also add them to the worker container to reduce copying.
