---
version: '3'
services:
  girder:
    volumes:
      # For local development, uncomment the set of mounts associated with the
      # local source files.  Adding the editable egg directories first allows
      # allow mounting source files from the host without breaking the internal
      # data.
      #- /home/dagutman/devel/dsa-wsi-deid:/opt/dsa-wsi-deid
      #- /home/dagutman/devel/nci-dsa-deid:/opt/nci-dsa-deid
      - ./wsi_deid_provision.py:/opt/digital_slide_archive/devops/dsa/wsi_deid_provision.py
      - ./provision.py:/opt/digital_slide_archive/devops/dsa/provision.py
      - ./importManifestSchema.json:/opt/digital_slide_archive/devops/dsa/importManifestSchema.json
      - ./provision.yaml:/opt/digital_slide_archive/devops/dsa/provision.yaml
      - ./homepage.md:/opt/digital_slide_archive/devops/dsa/homepage.md
      - $PWD/import:/import
      - $PWD/export:/export
      - ../..:/opt/nci-dsa-deid
    #    command: bash -c 'PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH" pip install /opt/nci-dsa-deid && PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH" python /opt/digital_slide_archive/devops/dsa/wsi_deid_provision.py && /opt/digital_slide_archive/devops/dsa/start_girder.sh '
    #command: bash -c 'PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH NPM_EXE=/root/.nvm/versions/node/v14.21.3/bin/npm " pip install -e /opt/nci-dsa-deid && PATH="/opt/venv/bin:/.pyenv/bin:/.pyenv/shims:$PATH"  /opt/digital_slide_archive/devops/dsa/start_girder.sh --rebuild-client ' # system.  Also add them to the worker container to reduce copying.
  deidhelper:
    image: dagutman/dsadeidhelperdev:latest
    ports:
      - 8050:8050
    environment:
      DSA_API_URL: https://10.240.138.8:8080/api/v1
